### ISSUE TITLE
Callables do not enforce required parameters

### ISSUE THREAD

**Issue by miki725** [pybee/batavia#101]
For example:

```python
def foo(a):
    print(a)
foo()
```

results in (traceback from Chrome):

```python
Traceback (most recent call last):
  File "/var/folders/jy/_hlv4sxd78nd0dlxq4p4zmxr0000gn/T/tmpbu2tr58w", line 3, in <module>
  File "/var/folders/jy/_hlv4sxd78nd0dlxq4p4zmxr0000gn/T/tmpbu2tr58w", line 2, in foo
NameError: local variable 'a' referenced before assignment
```

whereas correct Py behavior is:

```python
>>> def foo(a):
...     print(a)
...
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() missing 1 required positional argument: 'a'
```

**Comment by candeira** [comment]
I'd like to give this one a try. I guess this could be done this way:
- functions should be compiled as JS closures containing a list of *argnamesj
- on call, assert js!arguments.length == len(argnames)
- if it fails, use the actual *argnames tuple to index/slice the missing required arguments, or else complain "<functionname> takes exactly n arguments (m>n given)"

**Comment by candeira** [comment]
@tysonclugg started on this one yesterday. I'm de-dibbing it.
