### ISSUE TITLE
time.mktime needs to handle tm_isdst

### ISSUE THREAD

**Issue by ElSaico** [pybee/batavia#342]
Seems like Batavia's `mktime` is assuming the wrong timezone - all expected values are exactly one hour away!

```
======================================================================
FAIL: test_mktime (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bruno/PycharmProjects/batavia/tests/modules/test_time.py", line 203, in test_mktime
    self.assertCodeExecution(test_str)
  File "/home/bruno/PycharmProjects/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [99 chars]0))\n7200.0\n>>> seq = time.struct_time((1970,[53 chars].0\n' != '>>> [99 chars]0))\n10800.0\n>>> seq = time.struct_time((1970[55 chars].0\n'
  >>> import time
  >>> seq = (1970, 1, 1, 0, 0, 0, 0, 0, 0)
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))
- 7200.0
+ 10800.0
  >>> seq = time.struct_time((1970, 1, 1, 0, 0, 0, 0, 0, 0))
  >>> time.mktime(seq)
- 7200.0
+ 10800.0
 : Global context

======================================================================
FAIL: test_mktime_args (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bruno/PycharmProjects/batavia/tests/modules/test_time.py", line 226, in test_mktime_args
    self.assertCodeExecution(test_str)
  File "/home/bruno/PycharmProjects/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [124 chars]n10378800.0\n>>> time.mktime((1970, 1, 5, 0, 0[256 chars].0\n' != '>>> [124 chars]n10375200.0\n>>> time.mktime((1970, 1, 5, 0, 0[259 chars].0\n'
  >>> import time
  >>> time.mktime((1999, 1, 1, 0, 0, 0, 0, 0, -1))
  915156000.0
  >>> time.mktime((1970, 5, 1, 0, 0, 0, 0, 0, 1))
- 10378800.0
?     ^^
+ 10375200.0
?     ^^
  >>> time.mktime((1970, 1, 5, 0, 0, 0, 0, 0, -1))
- 352800.0
?   ^^
+ 356400.0
?   ^^
  >>> time.mktime((1970, 1, 1, 5, 0, 0, 0, 0, -1))
- 25200.0
?  ^^
+ 28800.0
?  ^^
  >>> time.mktime((1970, 1, 1, 0, 5, 0, 0, 0, -1))
- 7500.0
+ 11100.0
  >>> time.mktime((1970, 1, 1, 0, 0, 5, 0, 0, -1))
- 7205.0
+ 10805.0
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 5, 0, -1))
- 7200.0
+ 10800.0
 : Global context

======================================================================
FAIL: test_mktime_dst (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bruno/PycharmProjects/batavia/tests/modules/test_time.py", line 251, in test_mktime_dst
    self.assertCodeExecution(test_str)
  File "/home/bruno/PycharmProjects/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [73 chars]0))\n7200.0\ntrying month 2\n>>> time.mktime(([813 chars].0\n' != '>>> [73 chars]0))\n10800.0\ntrying month 2\n>>> time.mktime([814 chars].0\n'
  >>> import time
  trying month 1
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))
- 7200.0
+ 10800.0
  trying month 2
  >>> time.mktime((1970, 2, 1, 0, 0, 0, 0, 0, 0))
- 2685600.0
?    ^^
+ 2689200.0
?    ^^
  trying month 3
  >>> time.mktime((1970, 3, 1, 0, 0, 0, 0, 0, 0))
  5108400.0
  trying month 4
  >>> time.mktime((1970, 4, 1, 0, 0, 0, 0, 0, 1))
- 7786800.0
?    ^^
+ 7783200.0
?    ^^
  trying month 5
  >>> time.mktime((1970, 5, 1, 0, 0, 0, 0, 0, 1))
- 10378800.0
?     ^^
+ 10375200.0
?     ^^
  trying month 6
  >>> time.mktime((1970, 6, 1, 0, 0, 0, 0, 0, 1))
- 13057200.0
?     ^^
+ 13053600.0
?     ^^
  trying month 7
  >>> time.mktime((1970, 7, 1, 0, 0, 0, 0, 0, 1))
- 15649200.0
?     ^^
+ 15645600.0
?     ^^
  trying month 8
  >>> time.mktime((1970, 8, 1, 0, 0, 0, 0, 0, 1))
- 18327600.0
?     ^^
+ 18324000.0
?     ^^
  trying month 9
  >>> time.mktime((1970, 9, 1, 0, 0, 0, 0, 0, 1))
- 21006000.0
?     ^^
+ 21002400.0
?     ^^
  trying month 10
  >>> time.mktime((1970, 10, 1, 0, 0, 0, 0, 0, 1))
- 23598000.0
?     ^^
+ 23594400.0
?     ^^
  trying month 11
  >>> time.mktime((1970, 11, 1, 0, 0, 0, 0, 0, 1))
  26272800.0
  trying month 12
  >>> time.mktime((1970, 12, 1, 0, 0, 0, 0, 0, 0))
- 28864800.0
?      -
+ 28868400.0
?     +
 : Global context

======================================================================
FAIL: test_mktime_too_late (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bruno/PycharmProjects/batavia/tests/modules/test_time.py", line 397, in test_mktime_too_late
    """.format(hour=hour, second=second))
  File "/home/bruno/PycharmProjects/batavia/tests/utils.py", line 606, in assertJavaScriptExecution
    self.assertNotEqual(js_out, py_out, 'Global context')
AssertionError: '>>> import time\n>>> time.mktime((275760, 9, 12, 22, 0, 0, 0, 0, 1))\n### EXCEPTION ###\nOverflowError: signed integer is greater than maximum\n    test.py:4\n' == '>>> import time\n>>> time.mktime((275760, 9, 12, 22, 0, 0, 0, 0, 1))\n### EXCEPTION ###\nOverflowError: signed integer is greater than maximum\n    test.py:4\n' : Global context

----------------------------------------------------------------------
Ran 28 tests in 3.097s

FAILED (failures=4, expected failures=2)
```

**Comment by freakboy3742** [comment]
Interesting - thanks for the report. 

The broader problem of "solving all timezones" needs a database like pytz. However, the core functionality of mktime shouldn't be timezone dependent. So, the question becomes why UTC isn't being used on your machine.

**Comment by ElSaico** [comment]
Aaaaaaand eureka!

Turns out `mktime`'s current implementation misses one crucial attribute - namely `tm_isdst`, which is currently 1 when running `localtime` here and assumes the `BRT` timezone when initialized to 0.
...which opens a whole new can of worms about how to handle it properly. Ouch.

**Comment by freakboy3742** [comment]
Q: How do you tell if someone is a programmer?
A: Ask them if they have an opinion on timezones. If they start swearing, they're a programmer. 

:-)

Just checking - is this an issue with `mktime`, or with the *test* for `mktime`?

**Comment by ElSaico** [comment]
*sighs* Indeed.

It's an implementation issue - `tm_isdst` is relevant for us poor DST'ers, and the million-dollar question is how to map it properly to JavaScript.

Just peeked at the Emscripten source for some inspiration since this kind of low-level shenanigans is right on their alley, but their handling of `tm_isdst` only makes sense to whoever wrote it.

**Comment by ElSaico** [comment]
Mmmm. Since #339 vendors in `moment`, which knows how to handle DSTs properly, it seems better to just wait until it's accepted.

**Comment by jstoebel** [comment]
Thanks for catching this @ElSaico!

**Comment by jstoebel** [comment]
Here's a silly video to that seems apt to this issue: https://www.youtube.com/watch?v=k4EUTMPuvHo&feature=youtu.be

**Comment by jstoebel** [comment]
following up. Has this been resolved?

**Comment by freakboy3742** [comment]
I'm pretty sure this is now working - if it isn't, please let us know what timezone you're in (and whether DST is active).
