### ISSUE TITLE
Errors in time module

### ISSUE THREAD

**Issue by candeira** [pybee/batavia#356]
I just pulled a fresh master (265ef1ac0af970c30016452da7fb0c4e95fab7ae) and the tests for the time module fail:

```
(batavia)kandinski@desire:~/data/work/hack/pybee/batavia$ python setup.py test -s tests.modules.test_time
running test
running egg_info
writing dependency_links to batavia.egg-info/dependency_links.txt
writing top-level names to batavia.egg-info/top_level.txt
writing requirements to batavia.egg-info/requires.txt
writing batavia.egg-info/PKG-INFO
reading manifest file 'batavia.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'requirements*.txt'
writing manifest file 'batavia.egg-info/SOURCES.txt'
running build_ext
test_get_item (tests.modules.test_time.TimeTests) ... ok
test_gmtime_argument_range (tests.modules.test_time.TimeTests) ... ok
test_gmtime_bad_type (tests.modules.test_time.TimeTests) ... ok
test_gmtime_no_arg (tests.modules.test_time.TimeTests) ... ['>>> import time\n>>> time.gmtime()\ntime.struct_time(tm_year=2016, tm_mon=11, tm_mday=6, tm_hour=4, tm_min=11, tm_sec=51, tm_wday=-1, tm_yday=311, tm_isdst=0)\n', '>>> import time\n>>> time.gmtime()\ntime.struct_time(tm_year=2016, tm_mon=11, tm_mday=6, tm_hour=4, tm_min=11, tm_sec=51, tm_wday=6, tm_yday=311, tm_isdst=0)\n']
ok
test_gmtime_too_many_args (tests.modules.test_time.TimeTests) ... ok
test_gmtime_with_arg (tests.modules.test_time.TimeTests) ... ok
test_mktime (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_args (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_bad_input (tests.modules.test_time.TimeTests) ... ok
test_mktime_dst (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_no_overflow_error (tests.modules.test_time.TimeTests) ... ok
test_mktime_non_integer_types (tests.modules.test_time.TimeTests) ... ok
test_mktime_seq_wrong_length (tests.modules.test_time.TimeTests) ... ok
test_mktime_too_early (tests.modules.test_time.TimeTests) ... ok
test_mktime_too_late (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_wrong_arg_count (tests.modules.test_time.TimeTests) ... ok
test_sleep (tests.modules.test_time.TimeTests) ... ok
test_sleep_negative (tests.modules.test_time.TimeTests) ... ok
test_struct_time_attrs (tests.modules.test_time.TimeTests) ... ok
test_struct_time_bad_types (tests.modules.test_time.TimeTests) ... expected failure
test_struct_time_invalid (tests.modules.test_time.TimeTests) ... ok
test_struct_time_repr (tests.modules.test_time.TimeTests) ... ok
test_struct_time_str (tests.modules.test_time.TimeTests) ... ok
test_struct_time_too_long (tests.modules.test_time.TimeTests) ... ok
test_struct_time_too_short (tests.modules.test_time.TimeTests) ... ok
test_struct_time_valid (tests.modules.test_time.TimeTests) ... ok
test_struct_time_valid_lengths (tests.modules.test_time.TimeTests) ... ok
test_time (tests.modules.test_time.TimeTests) ... expected failure

======================================================================
FAIL: test_mktime (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 203, in test_mktime
    self.assertCodeExecution(test_str)
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [101 chars])\n-39600.0\n>>> seq = time.struct_time((1970,[55 chars].0\n' != '>>> [101 chars])\n-36000.0\n>>> seq = time.struct_time((1970,[55 chars].0\n'
  >>> import time
  >>> seq = (1970, 1, 1, 0, 0, 0, 0, 0, 0)
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))
- -39600.0
?   -
+ -36000.0
?    +
  >>> seq = time.struct_time((1970, 1, 1, 0, 0, 0, 0, 0, 0))
  >>> time.mktime(seq)
- -39600.0
?   -
+ -36000.0
?    +
 : Global context

======================================================================
FAIL: test_mktime_args (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 226, in test_mktime_args
    self.assertCodeExecution(test_str)
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [123 chars]\n10332000.0\n>>> time.mktime((1970, 1, 5, 0, [264 chars].0\n' != '>>> [123 chars]\n10328400.0\n>>> time.mktime((1970, 1, 5, 0, [264 chars].0\n'
  >>> import time
  >>> time.mktime((1999, 1, 1, 0, 0, 0, 0, 0, -1))
  915109200.0
  >>> time.mktime((1970, 5, 1, 0, 0, 0, 0, 0, 1))
- 10332000.0
?    - ^
+ 10328400.0
?     ^^
  >>> time.mktime((1970, 1, 5, 0, 0, 0, 0, 0, -1))
- 306000.0
?    -
+ 309600.0
?   +
  >>> time.mktime((1970, 1, 1, 5, 0, 0, 0, 0, -1))
- -21600.0
?  - ^
+ -18000.0
?   ^^
  >>> time.mktime((1970, 1, 1, 0, 5, 0, 0, 0, -1))
- -39300.0
?   ^^
+ -35700.0
?   ^^
  >>> time.mktime((1970, 1, 1, 0, 0, 5, 0, 0, -1))
- -39595.0
?    -
+ -35995.0
?   +
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 5, 0, -1))
- -39600.0
?   -
+ -36000.0
?    +
 : Global context

======================================================================
FAIL: test_mktime_dst (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 251, in test_mktime_dst
    self.assertCodeExecution(test_str)
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [75 chars])\n-39600.0\ntrying month 2\n>>> time.mktime(([813 chars].0\n' != '>>> [75 chars])\n-36000.0\ntrying month 2\n>>> time.mktime(([813 chars].0\n'
  >>> import time
  trying month 1
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))
- -39600.0
?   -
+ -36000.0
?    +
  trying month 2
  >>> time.mktime((1970, 2, 1, 0, 0, 0, 0, 0, 0))
- 2638800.0
+ 2642400.0
  trying month 3
  >>> time.mktime((1970, 3, 1, 0, 0, 0, 0, 0, 0))
- 5058000.0
+ 5061600.0
  trying month 4
  >>> time.mktime((1970, 4, 1, 0, 0, 0, 0, 0, 1))
  7736400.0
  trying month 5
  >>> time.mktime((1970, 5, 1, 0, 0, 0, 0, 0, 1))
- 10332000.0
?    - ^
+ 10328400.0
?     ^^
  trying month 6
  >>> time.mktime((1970, 6, 1, 0, 0, 0, 0, 0, 1))
- 13010400.0
?    - ^
+ 13006800.0
?     ^^
  trying month 7
  >>> time.mktime((1970, 7, 1, 0, 0, 0, 0, 0, 1))
- 15602400.0
+ 15598800.0
  trying month 8
  >>> time.mktime((1970, 8, 1, 0, 0, 0, 0, 0, 1))
- 18280800.0
+ 18277200.0
  trying month 9
  >>> time.mktime((1970, 9, 1, 0, 0, 0, 0, 0, 1))
- 20959200.0
?     ^^
+ 20955600.0
?     ^^
  trying month 10
  >>> time.mktime((1970, 10, 1, 0, 0, 0, 0, 0, 1))
- 23551200.0
+ 23547600.0
  trying month 11
  >>> time.mktime((1970, 11, 1, 0, 0, 0, 0, 0, 1))
  26226000.0
  trying month 12
  >>> time.mktime((1970, 12, 1, 0, 0, 0, 0, 0, 0))
- 28818000.0
?     ^^
+ 28821600.0
?    + ^
 : Global context

======================================================================
FAIL: test_mktime_too_late (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 397, in test_mktime_too_late
    """.format(hour=hour, second=second))
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 606, in assertJavaScriptExecution
    self.assertNotEqual(js_out, py_out, 'Global context')
AssertionError: '>>> import time\n>>> time.mktime((275760, 9, 12, 35, 0, 0, 0, 0, 1))\n### EXCEPTION ###\nOverflowError: signed integer is greater than maximum\n    test.py:4\n' == '>>> import time\n>>> time.mktime((275760, 9, 12, 35, 0, 0, 0, 0, 1))\n### EXCEPTION ###\nOverflowError: signed integer is greater than maximum\n    test.py:4\n' : Global context

----------------------------------------------------------------------
Ran 28 tests in 4.012s

FAILED (failures=4, expected failures=2)
(batavia)kandinski@desire:~/data/work/hack/pybee/batavia$ python setup.py test -s tests.modules.test_time | xcl
xclip            xclipboard       xclip-copyfile   xclip-cutfile    xclip-pastefile  xclock
(batavia)kandinski@desire:~/data/work/hack/pybee/batavia$ python setup.py test -s tests.modules.test_time | xcl
xclip            xclipboard       xclip-copyfile   xclip-cutfile    xclip-pastefile  xclock
(batavia)kandinski@desire:~/data/work/hack/pybee/batavia$ python setup.py test -s tests.modules.test_time | xcl
xclip            xclipboard       xclip-copyfile   xclip-cutfile    xclip-pastefile  xclock
(batavia)kandinski@desire:~/data/work/hack/pybee/batavia$ python setup.py test -s tests.modules.test_time | xclipboardError: another clipboard is already running

error: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
(batavia)kandinski@desire:~/data/work/hack/pybee/batavia$ python setup.py test -s tests.modules.test_time | xclip
warning: no files found matching 'requirements*.txt'
test_get_item (tests.modules.test_time.TimeTests) ... ok
test_gmtime_argument_range (tests.modules.test_time.TimeTests) ... ok
test_gmtime_bad_type (tests.modules.test_time.TimeTests) ... ok
test_gmtime_no_arg (tests.modules.test_time.TimeTests) ... ok
test_gmtime_too_many_args (tests.modules.test_time.TimeTests) ... ok
test_gmtime_with_arg (tests.modules.test_time.TimeTests) ... ok
test_mktime (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_args (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_bad_input (tests.modules.test_time.TimeTests) ... ok
test_mktime_dst (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_no_overflow_error (tests.modules.test_time.TimeTests) ... ok
test_mktime_non_integer_types (tests.modules.test_time.TimeTests) ... ok
test_mktime_seq_wrong_length (tests.modules.test_time.TimeTests) ... ok
test_mktime_too_early (tests.modules.test_time.TimeTests) ... ok
test_mktime_too_late (tests.modules.test_time.TimeTests) ... FAIL
test_mktime_wrong_arg_count (tests.modules.test_time.TimeTests) ... ok
test_sleep (tests.modules.test_time.TimeTests) ... ok
test_sleep_negative (tests.modules.test_time.TimeTests) ... ok
test_struct_time_attrs (tests.modules.test_time.TimeTests) ... ok
test_struct_time_bad_types (tests.modules.test_time.TimeTests) ... expected failure
test_struct_time_invalid (tests.modules.test_time.TimeTests) ... ok
test_struct_time_repr (tests.modules.test_time.TimeTests) ... ok
test_struct_time_str (tests.modules.test_time.TimeTests) ... ok
test_struct_time_too_long (tests.modules.test_time.TimeTests) ... ok
test_struct_time_too_short (tests.modules.test_time.TimeTests) ... ok
test_struct_time_valid (tests.modules.test_time.TimeTests) ... ok
test_struct_time_valid_lengths (tests.modules.test_time.TimeTests) ... ok
test_time (tests.modules.test_time.TimeTests) ... expected failure

======================================================================
FAIL: test_mktime (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 203, in test_mktime
    self.assertCodeExecution(test_str)
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [101 chars])\n-39600.0\n>>> seq = time.struct_time((1970,[55 chars].0\n' != '>>> [101 chars])\n-36000.0\n>>> seq = time.struct_time((1970,[55 chars].0\n'
  >>> import time
  >>> seq = (1970, 1, 1, 0, 0, 0, 0, 0, 0)
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))
- -39600.0
?   -
+ -36000.0
?    +
  >>> seq = time.struct_time((1970, 1, 1, 0, 0, 0, 0, 0, 0))
  >>> time.mktime(seq)
- -39600.0
?   -
+ -36000.0
?    +
 : Global context

======================================================================
FAIL: test_mktime_args (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 226, in test_mktime_args
    self.assertCodeExecution(test_str)
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [123 chars]\n10332000.0\n>>> time.mktime((1970, 1, 5, 0, [264 chars].0\n' != '>>> [123 chars]\n10328400.0\n>>> time.mktime((1970, 1, 5, 0, [264 chars].0\n'
  >>> import time
  >>> time.mktime((1999, 1, 1, 0, 0, 0, 0, 0, -1))
  915109200.0
  >>> time.mktime((1970, 5, 1, 0, 0, 0, 0, 0, 1))
- 10332000.0
?    - ^
+ 10328400.0
?     ^^
  >>> time.mktime((1970, 1, 5, 0, 0, 0, 0, 0, -1))
- 306000.0
?    -
+ 309600.0
?   +
  >>> time.mktime((1970, 1, 1, 5, 0, 0, 0, 0, -1))
- -21600.0
?  - ^
+ -18000.0
?   ^^
  >>> time.mktime((1970, 1, 1, 0, 5, 0, 0, 0, -1))
- -39300.0
?   ^^
+ -35700.0
?   ^^
  >>> time.mktime((1970, 1, 1, 0, 0, 5, 0, 0, -1))
- -39595.0
?    -
+ -35995.0
?   +
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 5, 0, -1))
- -39600.0
?   -
+ -36000.0
?    +
 : Global context

======================================================================
FAIL: test_mktime_dst (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 251, in test_mktime_dst
    self.assertCodeExecution(test_str)
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 504, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [75 chars])\n-39600.0\ntrying month 2\n>>> time.mktime(([813 chars].0\n' != '>>> [75 chars])\n-36000.0\ntrying month 2\n>>> time.mktime(([813 chars].0\n'
  >>> import time
  trying month 1
  >>> time.mktime((1970, 1, 1, 0, 0, 0, 0, 0, 0))
- -39600.0
?   -
+ -36000.0
?    +
  trying month 2
  >>> time.mktime((1970, 2, 1, 0, 0, 0, 0, 0, 0))
- 2638800.0
+ 2642400.0
  trying month 3
  >>> time.mktime((1970, 3, 1, 0, 0, 0, 0, 0, 0))
- 5058000.0
+ 5061600.0
  trying month 4
  >>> time.mktime((1970, 4, 1, 0, 0, 0, 0, 0, 1))
  7736400.0
  trying month 5
  >>> time.mktime((1970, 5, 1, 0, 0, 0, 0, 0, 1))
- 10332000.0
?    - ^
+ 10328400.0
?     ^^
  trying month 6
  >>> time.mktime((1970, 6, 1, 0, 0, 0, 0, 0, 1))
- 13010400.0
?    - ^
+ 13006800.0
?     ^^
  trying month 7
  >>> time.mktime((1970, 7, 1, 0, 0, 0, 0, 0, 1))
- 15602400.0
+ 15598800.0
  trying month 8
  >>> time.mktime((1970, 8, 1, 0, 0, 0, 0, 0, 1))
- 18280800.0
+ 18277200.0
  trying month 9
  >>> time.mktime((1970, 9, 1, 0, 0, 0, 0, 0, 1))
- 20959200.0
?     ^^
+ 20955600.0
?     ^^
  trying month 10
  >>> time.mktime((1970, 10, 1, 0, 0, 0, 0, 0, 1))
- 23551200.0
+ 23547600.0
  trying month 11
  >>> time.mktime((1970, 11, 1, 0, 0, 0, 0, 0, 1))
  26226000.0
  trying month 12
  >>> time.mktime((1970, 12, 1, 0, 0, 0, 0, 0, 0))
- 28818000.0
?     ^^
+ 28821600.0
?    + ^
 : Global context

======================================================================
FAIL: test_mktime_too_late (tests.modules.test_time.TimeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/modules/test_time.py", line 397, in test_mktime_too_late
    """.format(hour=hour, second=second))
  File "/home/kandinski/data/work/hack/pybee/batavia/tests/utils.py", line 606, in assertJavaScriptExecution
    self.assertNotEqual(js_out, py_out, 'Global context')
AssertionError: '>>> import time\n>>> time.mktime((275760, 9, 12, 35, 0, 0, 0, 0, 1))\n### EXCEPTION ###\nOverflowError: signed integer is greater than maximum\n    test.py:4\n' == '>>> import time\n>>> time.mktime((275760, 9, 12, 35, 0, 0, 0, 0, 1))\n### EXCEPTION ###\nOverflowError: signed integer is greater than maximum\n    test.py:4\n' : Global context

----------------------------------------------------------------------
Ran 28 tests in 3.814s

FAILED (failures=4, expected failures=2)
```

**Comment by candeira** [comment]
I wrote a commit to skip these tests, and found that they pass on CircleCI. Could it be a timezone issue? I'm in Australia, my laptop's set for AEDT:

```
kandinski@desire:~/batavia$ date
Sunday 6 November  20:35:56 AEDT 2016
```

In any case, the fact that the tests run differently in CI than on my laptop gives me pause. 

The difference between the cPython and the Batavia values for `mktime` is consistently 3600, which is the number of seconds in an hour, so that makes me think there is a bug in batavia's `mktime`.

**Comment by jstoebel** [comment]
I _believe_ this repeats [this ticket](https://github.com/pybee/batavia/issues/342). One solution raised by @ElSaico was to use moment.js to properly handle timezones. At the moment I am having trouble getting the CI to play nice with `moment`. (see [here](https://github.com/pybee/batavia/pull/339) If you have any thoughts on how to address this, I would love to hear them.

**Comment by candeira** [comment]
Yes, I didn't realise it was a repeat of the ticket, since I experienced it as a regression. Sorry for that.

I'll close this ticket and track the other one.
