### ISSUE TITLE
Test suite returns many AssertionErrors

### ISSUE THREAD

**Issue by Hiren-Mehta** [pybee/batavia#595]
The system in question is an Asus EeeBook X205TA running Windows with Python 3.4.4. The sandbox runs successfully but many tests, especially those in the tests.builtins.test_hash group fail, returning an AssertionError.

``python setup.py test -s tests.builtins.test_hash.BuiltinHashFunctionTest
s.test_None
C:\Python34\lib\site-packages\setuptools\dist.py:285: UserWarning: Normalizing '3.4.0-dev19' to '3.4.0.dev19'
  normalized_version,
running test
running egg_info
writing batavia.egg-info\PKG-INFO
writing dependency_links to batavia.egg-info\dependency_links.txt
writing top-level names to batavia.egg-info\top_level.txt
reading manifest file 'batavia.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Makefile'
warning: no files found matching 'requirements*.txt'
writing manifest file 'batavia.egg-info\SOURCES.txt'
running build_ext
building 'batavia.js'
test_None (tests.builtins.test_hash.BuiltinHashFunctionTests) ... FAIL

======================================================================
FAIL: test_None (tests.builtins.test_hash.BuiltinHashFunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\retailadmin\documents\github\batavia-dev\batavia\tests\utils.py", line 1238, in func
    substitutions=getattr(self, 'substitutions', SAMPLE_SUBSTITUTIONS)
  File "c:\users\retailadmin\documents\github\batavia-dev\batavia\tests\utils.py", line 1278, in assertBuiltinFunction
    run_in_function=False,
  File "c:\users\retailadmin\documents\github\batavia-dev\batavia\tests\utils.py", line 445, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> f = hash\n>>> x = None\n>>> f(x)\n0\n\n' != '>>> f = hash\n>>> x = None\n>>> f(x)\n-2052189012\n\n'
  >>> f = hash
  >>> x = None
  >>> f(x)
- 0
+ -2052189012

 : Global context: Error running f(x)

----------------------------------------------------------------------
Ran 1 test in 75.036s

FAILED (failures=1)``

**Comment by Hiren-Mehta** [comment]
Also, `npm install` had the following output:
`npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})`
