### ISSUE TITLE
AttributeError : module' object has no attribute 'TimeoutExpired'

### ISSUE THREAD

**Issue by vishal3410** [pybee/batavia#773]
## Expected Behavior
if the builtin is implemented:
`test_bool (tests.builtins.test_abs.BuiltinAbsFunctionTests) ... ok`

if the builtin is not implemented:
`test_abs_not_implemented (tests.builtins.test_abs.AbsTests) ... expected failure`

## Current Behavior
1.when running single test in builtins in vars function:
`/home/vishal/.pyenv/versions/3.5.0/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/home/vishal/.pyenv/versions/3.5.0/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'package_urls'
  warnings.warn(msg)
/home/vishal/pybee/venv/lib/python3.5/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '3.4.0-dev19' to '3.4.0.dev19'
  normalized_version,
running test
running egg_info
writing dependency_links to batavia.egg-info/dependency_links.txt
writing batavia.egg-info/PKG-INFO
writing top-level names to batavia.egg-info/top_level.txt
reading manifest file 'batavia.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Makefile'
warning: no files found matching 'requirements*.txt'
writing manifest file 'batavia.egg-info/SOURCES.txt'
running build_ext
building 'batavia.js' for development
ERROR

======================================================================
ERROR: setUpClass (tests.builtins.test_vars.BuiltinVarsFunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vishal/pybee/batavia/tests/utils.py", line 446, in setUpClass
    setUpSuite()
  File "/home/vishal/pybee/batavia/tests/utils.py", line 71, in setUpSuite
    raise Exception("Error compiling batavia sources: " + out.decode('ascii'))
Exception: Error compiling batavia sources: Caching is enabled.
Error: EACCES: permission denied, open '/home/vishal/pybee/batavia/dist/batavia.js'`

## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [ ] Ubuntu

**Comment by martica** [comment]
Sorry it's been such a long time since you posted with no reply.

To me it looks like you somehow don't have write permission to the directory where it is trying to output batavia.js. The following error suggests that to me.

```Error: EACCES: permission denied, open '/home/vishal/pybee/batavia/dist/batavia.js'```
