### ISSUE TITLE
8 errors when running tests on Fedora23

### ISSUE THREAD

**Issue by soerendip** [pybee/batavia#80]
I am on Fedora 23:   
Linux r2d2 4.4.6-301.fc23.x86_64 #1 SMP Wed Mar 30 16:43:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Used anaconda to install a python 3.5 environment.
I downloaded phantomjs for linux 64bit version 2.1.1

Followed the instructions at [here](http://batavia.readthedocs.io/en/latest/internals/contributing.html) and successfully ran the test server. When I run the tests `python setup.py test` I get 8 errors:
```

======================================================================
FAIL: test_subscr_dict (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 637, in func
    self.assertBinaryOperation(x=value, y=example, operation=operation, format=self.format)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 658, in assertBinaryOperation
    """ % kwargs, "Error running %(operation)s with x=%(x)s and y=%(y)s" % kwargs)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '### [30 chars] indices must be integers, not dict\n    test.py:3\n' != '### [30 chars] indices must be integers or slices, not dict\n    test.py:3\n'
  ### EXCEPTION ###
- TypeError: list indices must be integers, not dict
+ TypeError: list indices must be integers or slices, not dict
?                                         ++++++++++
      test.py:3
 : Global context: Error running x[y] with x=[] and y={}

======================================================================
FAIL: test_subscr_float (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 637, in func
    self.assertBinaryOperation(x=value, y=example, operation=operation, format=self.format)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 658, in assertBinaryOperation
    """ % kwargs, "Error running %(operation)s with x=%(x)s and y=%(y)s" % kwargs)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '### [31 chars]indices must be integers, not float\n    test.py:3\n' != '### [31 chars]indices must be integers or slices, not float\n    test.py:3\n'
  ### EXCEPTION ###
- TypeError: list indices must be integers, not float
+ TypeError: list indices must be integers or slices, not float
?                                         ++++++++++
      test.py:3
 : Global context: Error running x[y] with x=[] and y=2.3456

======================================================================
FAIL: test_subscr_list (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 637, in func
    self.assertBinaryOperation(x=value, y=example, operation=operation, format=self.format)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 658, in assertBinaryOperation
    """ % kwargs, "Error running %(operation)s with x=%(x)s and y=%(y)s" % kwargs)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '### [30 chars] indices must be integers, not list\n    test.py:3\n' != '### [30 chars] indices must be integers or slices, not list\n    test.py:3\n'
  ### EXCEPTION ###
- TypeError: list indices must be integers, not list
+ TypeError: list indices must be integers or slices, not list
?                                         ++++++++++
      test.py:3
 : Global context: Error running x[y] with x=[] and y=[]

======================================================================
FAIL: test_subscr_none (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 637, in func
    self.assertBinaryOperation(x=value, y=example, operation=operation, format=self.format)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 658, in assertBinaryOperation
    """ % kwargs, "Error running %(operation)s with x=%(x)s and y=%(y)s" % kwargs)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '### [34 chars]ices must be integers, not NoneType\n    test.py:3\n' != '### [34 chars]ices must be integers or slices, not NoneType\n    test.py:3\n'
  ### EXCEPTION ###
- TypeError: list indices must be integers, not NoneType
+ TypeError: list indices must be integers or slices, not NoneType
?                                         ++++++++++
      test.py:3
 : Global context: Error running x[y] with x=[] and y=None

======================================================================
FAIL: test_subscr_str (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 637, in func
    self.assertBinaryOperation(x=value, y=example, operation=operation, format=self.format)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 658, in assertBinaryOperation
    """ % kwargs, "Error running %(operation)s with x=%(x)s and y=%(y)s" % kwargs)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '### [29 chars]t indices must be integers, not str\n    test.py:3\n' != '### [29 chars]t indices must be integers or slices, not str\n    test.py:3\n'
  ### EXCEPTION ###
- TypeError: list indices must be integers, not str
+ TypeError: list indices must be integers or slices, not str
?                                         ++++++++++
      test.py:3
 : Global context: Error running x[y] with x=[] and y=""

======================================================================
FAIL: test_subscr_tuple (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 637, in func
    self.assertBinaryOperation(x=value, y=example, operation=operation, format=self.format)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 658, in assertBinaryOperation
    """ % kwargs, "Error running %(operation)s with x=%(x)s and y=%(y)s" % kwargs)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '### [31 chars]indices must be integers, not tuple\n    test.py:3\n' != '### [31 chars]indices must be integers or slices, not tuple\n    test.py:3\n'
  ### EXCEPTION ###
- TypeError: list indices must be integers, not tuple
+ TypeError: list indices must be integers or slices, not tuple
?                                         ++++++++++
      test.py:3
 : Global context: Error running x[y] with x=[] and y=(1, 2.3456, 'another')

======================================================================
FAIL: test_creation (tests.datatypes.test_dict.DictTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/datatypes/test_dict.py", line 33, in test_creation
    """)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '{}\n' != "{'a': 1}\n"
- {}
+ {'a': 1}
 : Global context

======================================================================
FAIL: test_getitem (tests.datatypes.test_dict.DictTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/swacker/pycon/beeware/batavia/tests/datatypes/test_dict.py", line 43, in test_getitem
    """)
  File "/home/swacker/pycon/beeware/batavia/tests/utils.py", line 448, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: "False\nTrue\n### EXCEPTION ###\nKeyError: 'a'\n    test.py:5\n" != 'True\nFalse\n1\n'
+ True
  False
+ 1
- True
- ### EXCEPTION ###
- KeyError: 'a'
-     test.py:5
 : Global context

----------------------------------------------------------------------
Ran 4146 tests in 548.626s

FAILED (failures=8, expected failures=3262)

```

**Comment by glasnt** [comment]
Thank you for this! I'll take a look

**Comment by glasnt** [comment]
OK! It looks like this is an interesting one. 

What I'm seeing here is differences in the strings that are outputted between what we expect from Python 3.4 and what you have

It's literally failing on a slightly differently worded comment:

```
- TypeError: list indices must be integers, not NoneType
+ TypeError: list indices must be integers or slices, not NoneType
```

Specifically, "or slices" is added. 

Can you run `python --version` so I can get the exact thing?

**Comment by soerendip** [comment]
Python 3.5.1 :: Continuum Analytics, Inc.

Will try the correct environment with python 3.4 ...

**Comment by glasnt** [comment]
@soerendip If you can use 3.4.2 and report back if things are still breaking, that'd be awesome

**Comment by soerendip** [comment]
I am trying 3.4.4 right now. I can do 3.4.2 too.

**Comment by glasnt** [comment]
Please let me know if either have issues. 

There are Big Design Decisions as to the specific version happening so this will be very useful information

**Comment by soerendip** [comment]
3.4.4. runs all tests OK.

**Comment by glasnt** [comment]
Closing as per last comment. In the interests of issue cleanliness, @soerendip, if you encounter different Fedora issues, please open a new issue.
