### ISSUE TITLE
Running Batavia in Vagrant Box - Broken Pipe

### ISSUE THREAD

**Issue by lisroach** [pybee/batavia#81]
Hello!

When running the test suite for batavia, `python setup.py test`, I get 836 failures in addition to the 3262 expected failures. It appears that all of the failures are "Broken Pipe" errors. 

My environment:

Windows 7 laptop, running a Vagrant box
Vagrant version: 1.8.1
Virtualbox Version: 5.0.2
Linux Version: Ubuntu Trusty 14.04
Python Version: 3.4.3 (in a virtualenv)

Error example:

```
======================================================================
FAIL: test_js_code (tests.test_utils.JavaScriptBootstrapTests)
You can supply JavaScript code and use it from within Python
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/trusty_backup/batavia/tutorial/batavia-dev/batavia/tests/utils.py", line 529, in assertJavaScriptExecution
    args=args
  File "/vagrant/trusty_backup/batavia/tutorial/batavia-dev/batavia/tests/utils.py", line 275, in runAsJavaScript
    on_fail="Unable to create webpage."
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/trusty_backup/batavia/tutorial/batavia-dev/batavia/tests/test_utils.py", line 234, in test_js_code
    """,
  File "/vagrant/trusty_backup/batavia/tutorial/batavia-dev/batavia/tests/utils.py", line 532, in assertJavaScriptExecution
    self.fail(e)
AssertionError: [Errno 32] Broken pipe
```

Thank you for your help!

**Comment by glasnt** [comment]
Thank you for logging this bug!

I understand you're having on-site help with this. If you work out anything more, please update this issue

**Comment by miki725** [comment]
@lisroach do you have `phantomjs` installed? Ive seen similar issues related to that
